$source = Get-Content 'Assets/Survivor/Scripts/SurvivorGame.cs' -Raw
$source = $source.Replace('public sealed class SurvivorGame', 'public sealed partial class SurvivorGame')
$source = $source.Replace('public float life; }', 'public float life, power; public HashSet<Enemy> hit = new HashSet<Enemy>(); }')
$source = $source.Replace('UpdateCamera(true);' + "`n        }", 'UpdateCamera(true);' + "`n        }")
$source = $source.Replace('notice = "Selviä viisi minuuttia!"; noticeUntil = 5; UpdateCamera(true);', 'ResetProgression(); notice = "Valitse aloitusase"; noticeUntil = 5; UpdateCamera(true);')
$source = $source.Replace('&& !Finished) ShopOpen', '&& !Finished && !Selecting && PendingChoices == 0) ShopOpen')
$source = $source.Replace('if (ShopOpen) return;', 'if (ShopOpen || Selecting || PendingChoices > 0) return;')
$source = $source.Replace('if (Elapsed >= roundDuration) { Finished = true; return; }', 'TickProgression(dt); if (Finished) return;')
$source = $source.Replace('Health - (e.elite ? 18 : 9)', 'Health - Mathf.Max(1, (e.elite ? 18 : 9) - Armor)')
$source = $source.Replace('if (Health <= 0) { Finished = true; return; }', 'if (Health <= 0) { FinishRun(); return; }')
$source = $source.Replace('Attack(); attackTimer', 'AttackWeapons(); attackTimer')
$source = $source.Replace('new Vector3(6, .025f, 6) *', 'new Vector3(8 * Size, .025f, 8 * Size) *')
$source = $source.Replace('health = (elite ? 85 : 24) * (1 + Elapsed / 160), speed = (elite ? 2.2f : 3.1f) + Mathf.Min(2, Elapsed / 120)', 'health = (elite ? 85 : 24) * (1 + Elapsed / 240) * curse * (1 + .3f * (Area - 1)), speed = ((elite ? 2.2f : 3.1f) + Mathf.Min(2, Elapsed / 120)) * curse')
$start = $source.IndexOf('        void Attack()')
$end = $source.IndexOf('        void UpdateBolts', $start)
$source = $source.Remove($start, $end - $start)
$source = $source.Replace('foreach (var e in enemies)' , 'foreach (var e in enemies)')
$source = $source.Replace('                foreach (var e in enemies)' + "`r`n                {", '                foreach (var e in new List<Enemy>(enemies))' + "`r`n                {")
$source = $source.Replace('                foreach (var e in enemies)' + "`n                {", '                foreach (var e in new List<Enemy>(enemies))' + "`n                {")
$source = $source.Replace('if ((e.body.position - (start + segment * t)).sqrMagnitude < (e.elite ? 1.2f : .7f))', 'if (!b.hit.Contains(e) && (e.body.position - (start + segment * t)).sqrMagnitude < (e.elite ? 1.2f : .7f) * Size * Size)')
$source = $source.Replace('{ Hit(e, damage); b.life = 0; break; }', '{ b.hit.Add(e); Hit(e, b.power); }')
$source = $source.Replace('e.health -= amount;', 'if (Random.value < CritChance) amount *= 2; e.health -= amount;')
$source = $source.Replace('int value = e.elite ? 5 : 1;', 'if (e == boss) { boss = null; BossDefeated = true; bossKills++; notice = "Bossi voitettu! Palaa siniselle portaalille."; noticeUntil = Elapsed + 8; }' + "`n            int value = e.elite ? 5 : 1;")
$start = $source.IndexOf('                Experience -= NextLevel;')
$end = $source.IndexOf("`n            }", $start)
$source = $source.Remove($start, $end - $start).Insert($start, '                Experience -= NextLevel; Level++; PendingChoices++;' + "`n                if (choices.Count == 0) RollChoices();")
$source = $source.Replace('if (!ShopOpen || Finished || index', 'if (!ShopOpen || Finished || Selecting || PendingChoices > 0 || index')
$source = $source.Replace(' + " / 05:00"', ' + " / RUN"')
$source = $source.Replace('if (ShopOpen || Finished)', 'if ((ShopOpen || Finished) && !Selecting && PendingChoices == 0)')
$source = $source.Replace('                    if (GUI.Button(new Rect(380,380,520,60)', '                    GUI.Label(new Rect(380,305,520,40), "+" + EarnedSilver + " Silver tältä kierrokselta", textStyle);' + "`n                    DrawLegacy(380, 460);`n                    if (GUI.Button(new Rect(380,380,520,60)")
$source = $source.Replace('            if (Elapsed < noticeUntil)', '            if (Elapsed < noticeUntil)')
$start = $source.IndexOf('        static void Bar(')
$prior = $source.LastIndexOf('        }', $start)
$source = $source.Insert($prior, "            if (!Finished) DrawProgression();`n")
Set-Content 'PrototypeTools/SurvivorGame.v2.cs' -Value $source -Encoding utf8
